//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkaaEditorUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkaaEditorUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For MultiColumnComboBox:
        ///http://www.codeproject.com/Articles/19781/A-data-bound-multi-column-combobox
        ///
        ////********************************************************************************
        ///* Copyright (c) 2007, Nish Nishant
        ///* All rights reserved.
        ///* 
        ///* Redistribution and use in source and binary forms, with or without 
        ///* modification, are permitted provided that the following conditions are met:
        ///* 
        ///* 1. Redistributions of source code must retain the above copyright notice, 
        ///*    this list of condition [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSD_2_Clause_License {
            get {
                return ResourceManager.GetString("BSD_2_Clause_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ********************************************************************************
        ///
        ///This license applies to all SkaaEditor and 7KAA content, unless otherwise noted.
        ///
        ///********************************************************************************
        ///
        ///                    GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, bu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GPLv3 {
            get {
                return ResourceManager.GetString("GPLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_modern {
            get {
                object obj = ResourceManager.GetObject("logo_modern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *******************************************************************************
        ///
        ///This license applies to Cyotek Ltd&apos;s ImageBox which is bundled with SkaaEditor.
        ///
        ///*******************************************************************************
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright © 2013-2015 Cyotek Ltd.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///the Software without restriction, includi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MIT_License {
            get {
                return ResourceManager.GetString("MIT_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pal_std {
            get {
                object obj = ResourceManager.GetObject("pal_std", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon skaa {
            get {
                object obj = ResourceManager.GetObject("skaa", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon skaa_modern {
            get {
                object obj = ResourceManager.GetObject("skaa_modern", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] std {
            get {
                object obj = ResourceManager.GetObject("std", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
